update text coupon on payment flow bourse
FJNR-inc/Blitz-Website pull request #169
Opened 2020-11-30 11:32 UTC by Jerome-Celle

| Q                                                      | R
| ------------------------------------------ | -------------------------------------------
| Type of contribution ?                      |   Enhancement
| Tickets (_issues_) concerned               | [TV-338](https://fjnr-inc.atlassian.net/browse/TV-338)

---

## What have you changed ?
...

## How did you change it ?
...

## Screenshots
...

## Verification :
 -  [x] My branch name respect the standard defined in `CONTRIBUTING.md`
 -  [x] This Pull-Request fully meets the requirements defined in the issue
 -  [ ] I added or modified the attached tests

2020-11-30 17:48 UTC, RignonNoel requested changes
The `Files changed` section of Github detect a lot of change in the HTML and CSS, are you sure you did not change the line end ?

2020-11-30 17:48 UTC, RignonNoel commented on src/assets/i18n/fr.json
> +  "retreat-cart.labels.grant_code": "code pour accéder à votre bourse ou de votre certificat-cadeau",
Cette phrase n'est pas très française ou c'est moi qui est un problème avec le "de" ?

Ne serais-ce pas plutôt: "code pour accéder à votre bourse ou votre certificat-cadeau`"

2020-11-30 19:11 UTC, Jerome-Celle commented on src/assets/i18n/fr.json
> +  "retreat-cart.labels.grant_code": "code pour accéder à votre bourse ou de votre certificat-cadeau",
@RignonNoel Ouais, j'suis assez d'accord! Apres texte du client tel quel, donc comme tu le sens si je corrige ou pas :)

2020-12-01 00:31 UTC, RignonNoel commented on src/assets/i18n/fr.json
> +  "retreat-cart.labels.grant_code": "code pour accéder à votre bourse ou de votre certificat-cadeau",
J'ai ping Melanie, elle va mitiger le probleme

2020-12-02 13:27 UTC, RignonNoel approved these changes

2020-12-02 13:27 UTC, merged